--- 
- hosts: 155.138.217.199
  tasks:
    - name: install iis
      win_feature:
        name: "web-server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
    - name: create physical path for iis website's source
      win_file: 
        path: c:\inetpub\wwwroot\testansible 
        state: directory
    - name: create new website
      win_iis_website:
        name: "testansible"
        state: started
        port: 81
        physical_path: c:\inetpub\wwwroot\testansible
    
