--- 
- hosts: all
  tasks:
    - name: install iis
      win_feature:
        name: "web-server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
    - name: create physical path for iis website's source
      win_file: 
        path: c:\inetpub\wwwroot\csharpguitar 
        state=directory    
    
